# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadFileshareArtifacts@1
  inputs:
    filesharePath: 'https://download.gnome.org/sources/gtk/4.8/'
    artifactName: 'gtk-4.8.1.tar.xz'
    itemPattern: 'gtk-4.8.1.tar.xz'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: 'gtk-4.8.1.tar.xz'
    destinationFolder: 'gtk'
    cleanDestinationFolder: true
    overwriteExistingFiles: false
    
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
